// <auto-generated />
namespace PressAgencySystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addingImageUploadInPostModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addingImageUploadInPostModel));
        
        string IMigrationMetadata.Id
        {
            get { return "202106040109314_addingImageUploadInPostModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
